// Simplify Natural Earth 1:50m countries into one TopoJSON layer keyed by ISO 3166-1 alpha-3 (src/geo.js).
// China, Taiwan, Hong Kong and Macao come from the DataV outline (as in popflow), so each keeps its own data.
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const iso = require('i18n-iso-countries');

const here = p => new URL(p, import.meta.url).pathname;
const cache = here('../.cache/'), tmp = here('../.cache/tmp/');
rmSync(tmp, { recursive: true, force: true }); mkdirSync(tmp, { recursive: true });
const ms = (...args) => execFileSync(here('../node_modules/.bin/mapshaper'), args, { stdio: ['ignore', 'ignore', 'inherit'] });

ms('-i', cache + 'world50.json', '-simplify', '10%', 'keep-shapes', '-o', 'format=geojson', tmp + 'world.json', 'target=countries');
// mainland provinces dissolved into one outline; drop the nine-dash-line layer
ms('-i', cache + 'cn.json', '-filter', 'adcode != "100000_JD" && +adcode < 710000', '-dissolve', '-simplify', '6%', 'keep-shapes', '-o', 'format=geojson', tmp + 'cnm.json');
ms('-i', cache + 'cn.json', '-filter', 'adcode != "100000_JD" && +adcode >= 710000', '-filter-fields', 'adcode', '-simplify', '20%', 'keep-shapes', '-o', 'format=geojson', tmp + 'cns.json');

const load = f => JSON.parse(readFileSync(tmp + f, 'utf8'));
const NO_ISO = { Kosovo: 'XKX', Somaliland: 'SOM' };  // Somaliland is shaded as part of Somalia
const DROP = new Set(['CHN', 'TWN', 'HKG', 'MAC', 'ATA']);
const world = load('world.json');
world.features = world.features.flatMap(f => {
  const n = f.properties.name, k = f.id ? iso.numericToAlpha3(f.id) : NO_ISO[n];
  delete f.id;
  if (DROP.has(k) || n === 'Antarctica') return [];
  f.properties = { k: k || null, n };
  return [f];
});
const SAR = { 710000: ['TWN', 'Taiwan'], 810000: ['HKG', 'Hong Kong'], 820000: ['MAC', 'Macao'] };
const cnm = load('cnm.json'), cns = load('cns.json');  // dissolve without fields writes a bare GeometryCollection
cnm.features = cnm.geometries.map(geometry => ({ type: 'Feature', geometry, properties: { k: 'CHN', n: 'China' } }));
cns.features.forEach(f => { const [k, n] = SAR[f.properties.adcode]; f.properties = { k, n }; });
world.features.push(...cnm.features, ...cns.features);
writeFileSync(tmp + 'all.geojson', JSON.stringify(world));
ms('-i', tmp + 'all.geojson', '-rename-layers', 'c', '-o', 'format=topojson', 'quantization=20000', tmp + 'all.json');
const topology = JSON.parse(readFileSync(tmp + 'all.json', 'utf8'));
writeFileSync(here('../src/geo.js'), '// Generated by pipeline/build_geo.mjs from Natural Earth 1:50m (world-atlas) and the DataV China outline.\nconst GEO = ' + JSON.stringify(topology) + ';\n');
const keys = topology.objects.c.geometries.map(g => g.properties.k);
console.log('geo.js', (JSON.stringify(topology).length / 1024).toFixed(0) + ' KB,', keys.length, 'features,', new Set(keys.filter(Boolean)).size, 'ISO codes; unkeyed:',
  topology.objects.c.geometries.filter(g => !g.properties.k).map(g => g.properties.n).join(', '));
