// Simplify the three boundary sources into one TopoJSON (src/geo.js) and write unit centroids
// (pipeline/centroids.json) for the gravity model. Input: popflow/.cache (see fetch.sh).
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { geoCentroid, geoArea } from 'd3-geo';
import * as topo from 'topojson-client';

const here = p => new URL(p, import.meta.url).pathname;
const cache = here('../.cache/'), tmp = here('../.cache/tmp/');
rmSync(tmp, { recursive: true, force: true }); mkdirSync(tmp, { recursive: true });
const ms = (...args) => execFileSync(here('../node_modules/.bin/mapshaper'), args, { stdio: ['ignore', 'ignore', 'inherit'] });

// world countries (background + Europe), US states, China provinces (drop the nine-dash-line layer)
ms('-i', cache + 'world50.json', '-simplify', '10%', 'keep-shapes', '-o', 'format=geojson', tmp + 'world.json', 'target=countries');
ms('-i', cache + 'us10.json', '-simplify', '18%', 'keep-shapes', '-o', 'format=geojson', tmp + 'us.json', 'target=states');
ms('-i', cache + 'cn.json', '-filter', 'adcode != "100000_JD"', '-filter-fields', 'adcode,name', '-simplify', '5%', 'keep-shapes', '-o', 'format=geojson', tmp + 'cn.json');

const load = f => JSON.parse(readFileSync(tmp + f, 'utf8'));
const world = load('world.json'), us = load('us.json'), cn = load('cn.json');
// tag each feature with a key the data side uses: ISO numeric (world), state name (US), adcode (China)
world.features.forEach(f => { f.properties = { k: f.id ?? (f.properties.name === 'Kosovo' ? '688' : null), n: f.properties.name }; delete f.id; });
us.features.forEach(f => { f.properties = { k: f.properties.name }; delete f.id; });
cn.features.forEach(f => { f.properties = { k: String(f.properties.adcode), n: f.properties.name }; });
// Drop the US and China outlines from the world layer; the detailed layers replace them.
world.features = world.features.filter(f => !['840', '156', 'Antarctica'].includes(f.properties.k) && f.properties.n !== 'Antarctica');
writeFileSync(tmp + 'w.json', JSON.stringify(world));
writeFileSync(tmp + 'u.json', JSON.stringify(us));
writeFileSync(tmp + 'c.json', JSON.stringify(cn));
ms('-i', tmp + 'w.json', tmp + 'u.json', tmp + 'c.json', 'combine-files', '-rename-layers', 'world,us,cn',
  '-o', 'format=topojson', 'quantization=20000', tmp + 'all.json');
const topology = JSON.parse(readFileSync(tmp + 'all.json', 'utf8'));
writeFileSync(here('../src/geo.js'), '// Generated by pipeline/build_geo.mjs from Natural Earth (world-atlas), us-atlas and DataV boundaries.\nconst GEO = ' + JSON.stringify(topology) + ';\n');

// centroid of the largest polygon, so France sits in France rather than mid-Atlantic
const centroids = {};
const biggest = f => {
  const g = f.geometry;
  if (g.type !== 'MultiPolygon') return f;
  let best = null, area = -1;
  for (const c of g.coordinates) { const p = { type: 'Polygon', coordinates: c }; const a = geoArea(p); if (a > area) { area = a; best = p; } }
  return { type: 'Feature', geometry: best };
};
for (const [layer, prefix] of [['world', 'EU-'], ['us', 'US-'], ['cn', 'CN-']]) {
  for (const f of topo.feature(topology, topology.objects[layer]).features) centroids[layer + ':' + f.properties.k] = geoCentroid(biggest(f));
}
writeFileSync(here('centroids.raw.json'), JSON.stringify(centroids));
console.log('geo.js', (JSON.stringify(topology).length / 1024).toFixed(0) + ' KB', Object.keys(centroids).length, 'centroids');
